version: '3.8'

services:
  airfrance-api:
    container_name: airfrance-api
    build:
      context: ./AirFranceKLMAPI
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    restart: unless-stopped
    networks:
      - AirFranceNetwork
      - MetricsNetwork
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_DOMAIN=${API_DOMAIN}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AIRFRANCEKLM_API_KEY_1=${AIRFRANCEKLM_API_KEY_1}
      - AIRFRANCEKLM_API_KEY_2=${AIRFRANCEKLM_API_KEY_2}
      - AIRFRANCEKLM_API_KEY_3=${AIRFRANCEKLM_API_KEY_3}
      - AIRFRANCEKLM_API_KEY_4=${AIRFRANCEKLM_API_KEY_4}
      - AIRFRANCEKLM_API_KEY_5=${AIRFRANCEKLM_API_KEY_5}
      - AIRFRANCEKLM_API_KEY_6=${AIRFRANCEKLM_API_KEY_6}
      - AIRFRANCEKLM_API_KEY_7=${AIRFRANCEKLM_API_KEY_7}
      - AIRFRANCEKLM_API_KEY_8=${AIRFRANCEKLM_API_KEY_8}
      - AIRFRANCEKLM_API_KEY_9=${AIRFRANCEKLM_API_KEY_9}
      - CACHE=${CACHE}
      - PROMETHEUS_AUTH=${PROMETHEUS_AUTH}
      - HISTORICAL=${HISTORICAL}
    volumes:
      - ./logs:/AirFranceKLMAPI/logs

  airfrance-db:
    image: postgres:15-alpine
    container_name: airfrance-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./AirFranceKLMAPI/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./AirFranceKLMAPI/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: unless-stopped
    expose:
      - 10001
    ports:
      - 10001:5432
    command: -p 10001
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 10001"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - AirFranceNetwork

networks:
  AirFranceNetwork:
    external: true
  MetricsNetwork:
    external: true
